#!/bin/bash


apt-get update
apt-get install virtualbox-4.2
# Extension pack instalieren
VBOXVERSION=`dpkg -l virtualbox-4.2  |grep ii | awk '{print $3}' | awk -F'~' '{print $1}'`
EXTPACKURI="http://download.virtualbox.org/virtualbox/4.2.12/Oracle_VM_VirtualBox_Extension_Pack-${VBOXVERSION}.vbox-extpack"
EXTPACKTMP=/tmp/Oracle_VM_VirtualBox_Extension_Pack-${VBOXVERSION}.vbox-extpack
wget $EXTPACKURI -O $EXTPACKTMP
vboxmanage extpack install --replace $EXTPACKTMP
rm $EXTPACKTMP
